### ISSUE TITLE
Easier downloads from UnityHub

### ISSUE THREAD

**Issue by NightmareCorporation** [pardeike/RimWorld4Debugging#2]
It's probably possible for electron to simply pass the detected version directly to UnityHub via Windows commands: 
![image](https://user-images.githubusercontent.com/19686118/195114348-e3a65031-e96d-4644-9173-c98d09046c54.png)
![image](https://user-images.githubusercontent.com/19686118/195114106-53de817d-4e66-43c9-b810-44c9d46f4765.png)
![image](https://user-images.githubusercontent.com/19686118/195114156-76f4107f-9480-4c86-a93d-36f2cf660df5.png)

**Comment by pardeike** [comment]
Oh interesting, I did not know that. I will explore,
