### ISSUE TITLE
Finished unity install not auto-detected

### ISSUE THREAD

**Issue by NightmareCorporation** [pardeike/RimWorld4Debugging#3]
After finishing installation in UnityHub of the suggested version, RW4D does not automatically continue, going one step back and then forwards again picks up the installation.

![image](https://user-images.githubusercontent.com/19686118/195118595-04d84117-070b-4de7-8aa9-71f7471d4209.png)

**Comment by pardeike** [comment]
I think I forgot the refresh button (or some polling in the background). Could also be related to #4
