### ISSUE TITLE
Manual path entry to Unity Editor

### ISSUE THREAD

**Issue by NightmareCorporation** [pardeike/RimWorld4Debugging#4]
I managed to break my automatic detection of the unity editor entirely by moving the installation directory of Unity Hub installed things (I can not afford to waste the C: space).

As a result RW4D does not pick up the installed unity editor at all, having a manual selection here would make it possible for me to continue. Going back / forward in the steps does not solve this issue either.

![image](https://user-images.githubusercontent.com/19686118/195122903-e53f7f7c-b6e7-441b-9257-5b57a56b064a.png)

**Comment by pardeike** [comment]
Yeah, it's kind of tricky to "find an application in Windows". I might have to provide a fix by letting you start Unity Hub and so I can go though all running processes and find its root directory (just like I did with RimWorld)

**Comment by NightmareCorporation** [comment]
> Yeah, it's kind of tricky to "find an application in Windows". I might have to provide a fix by letting you start Unity Hub and so I can go though all running processes and find its root directory (just like I did with RimWorld)

This approach may cause issues for users that install the hub on one drive and editors on another, unless you can manage to read out the configuration data of the Hub to detect the editor installation destination. A solid fallback for this kind of stuff would be to provide an input-field to manually enter the path

**Comment by pardeike** [comment]
I think default is "" which means its relative to the hub itself, otherwise is your custom location as path

**Comment by NightmareCorporation** [comment]
Looks like you're right with that!

![image](https://user-images.githubusercontent.com/19686118/195137153-84273c17-f69d-424b-bf31-74794469d0a7.png)
